root = "."
testdata_dir = ""
tmp_dir = "build"

[build]
  args_bin = []
  bin = "build/app"
  cmd = "mage swag && go build -o build/app ./cmd/app"
  delay = 0
  exclude_dir = ["build", "magefiles", "db", "packages", "solid", "docs", "node_modules", ".vscode"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
