version: "3"

services:
  app:
    image: registry.fly.io/pms:latest
    restart: always
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      ENVIRONMENT: staging
    ports:
      - "3000:3000"
    # volumes:
    #   - ./tmp/litefs:/litefs
