/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The `iat` (Issued At) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6
 *
 * @export
 * @interface AuthClaimsIat
 */
export interface AuthClaimsIat {
	/**
	 * @memberof AuthClaimsIat
	 * @type {string}
	 */
	timeTime?: string;
}

/** Check if a given object implements the AuthClaimsIat interface. */
export function instanceOfAuthClaimsIat(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function AuthClaimsIatFromJSON(json: any): AuthClaimsIat {
	return AuthClaimsIatFromJSONTyped(json, false);
}

export function AuthClaimsIatFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthClaimsIat {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		timeTime: !exists(json, "time.Time") ? undefined : json["time.Time"],
	};
}

export function AuthClaimsIatToJSON(value?: AuthClaimsIat | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		"time.Time": value.timeTime,
	};
}
