/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The `exp` (Expiration Time) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4
 *
 * @export
 * @interface AuthClaimsExp
 */
export interface AuthClaimsExp {
	/**
	 * @memberof AuthClaimsExp
	 * @type {string}
	 */
	timeTime?: string;
}

/** Check if a given object implements the AuthClaimsExp interface. */
export function instanceOfAuthClaimsExp(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function AuthClaimsExpFromJSON(json: any): AuthClaimsExp {
	return AuthClaimsExpFromJSONTyped(json, false);
}

export function AuthClaimsExpFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthClaimsExp {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		timeTime: !exists(json, "time.Time") ? undefined : json["time.Time"],
	};
}

export function AuthClaimsExpToJSON(value?: AuthClaimsExp | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		"time.Time": value.timeTime,
	};
}
