/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The `nbf` (Not Before) claim. See https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5
 *
 * @export
 * @interface AuthClaimsNbf
 */
export interface AuthClaimsNbf {
	/**
	 * @memberof AuthClaimsNbf
	 * @type {string}
	 */
	timeTime?: string;
}

/** Check if a given object implements the AuthClaimsNbf interface. */
export function instanceOfAuthClaimsNbf(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function AuthClaimsNbfFromJSON(json: any): AuthClaimsNbf {
	return AuthClaimsNbfFromJSONTyped(json, false);
}

export function AuthClaimsNbfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthClaimsNbf {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		timeTime: !exists(json, "time.Time") ? undefined : json["time.Time"],
	};
}

export function AuthClaimsNbfToJSON(value?: AuthClaimsNbf | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		"time.Time": value.timeTime,
	};
}
