/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ModelsBook } from "./ModelsBook";
import { ModelsBookFromJSON, ModelsBookFromJSONTyped, ModelsBookToJSON } from "./ModelsBook";

/**
 * @export
 * @interface ControllersBooksListResponse
 */
export interface ControllersBooksListResponse {
	/**
	 * @memberof ControllersBooksListResponse
	 * @type {ModelsBook[]}
	 */
	books: Array<ModelsBook>;
}

/** Check if a given object implements the ControllersBooksListResponse interface. */
export function instanceOfControllersBooksListResponse(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "books" in value;

	return isInstance;
}

export function ControllersBooksListResponseFromJSON(json: any): ControllersBooksListResponse {
	return ControllersBooksListResponseFromJSONTyped(json, false);
}

export function ControllersBooksListResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ControllersBooksListResponse {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		books: (json["books"] as Array<any>).map(ModelsBookFromJSON),
	};
}

export function ControllersBooksListResponseToJSON(value?: ControllersBooksListResponse | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		books: (value.books as Array<any>).map(ModelsBookToJSON),
	};
}
