/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * @export
 * @interface ControllersAuthTokens
 */
export interface ControllersAuthTokens {
	/**
	 * @memberof ControllersAuthTokens
	 * @type {string}
	 */
	authorization: string;
}

/** Check if a given object implements the ControllersAuthTokens interface. */
export function instanceOfControllersAuthTokens(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "authorization" in value;

	return isInstance;
}

export function ControllersAuthTokensFromJSON(json: any): ControllersAuthTokens {
	return ControllersAuthTokensFromJSONTyped(json, false);
}

export function ControllersAuthTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersAuthTokens {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		authorization: json["authorization"],
	};
}

export function ControllersAuthTokensToJSON(value?: ControllersAuthTokens | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		authorization: value.authorization,
	};
}
