/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * @export
 * @interface ControllersAuthPostSignInRequest
 */
export interface ControllersAuthPostSignInRequest {
	/**
	 * @memberof ControllersAuthPostSignInRequest
	 * @type {string}
	 */
	email: string;
	/**
	 * @memberof ControllersAuthPostSignInRequest
	 * @type {string}
	 */
	password: string;
}

/** Check if a given object implements the ControllersAuthPostSignInRequest interface. */
export function instanceOfControllersAuthPostSignInRequest(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "email" in value;
	isInstance = isInstance && "password" in value;

	return isInstance;
}

export function ControllersAuthPostSignInRequestFromJSON(json: any): ControllersAuthPostSignInRequest {
	return ControllersAuthPostSignInRequestFromJSONTyped(json, false);
}

export function ControllersAuthPostSignInRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ControllersAuthPostSignInRequest {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		email: json["email"],
		password: json["password"],
	};
}

export function ControllersAuthPostSignInRequestToJSON(value?: ControllersAuthPostSignInRequest | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		email: value.email,
		password: value.password,
	};
}
