/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * @export
 * @interface ControllersAuthPostRequest
 */
export interface ControllersAuthPostRequest {
	/**
	 * @memberof ControllersAuthPostRequest
	 * @type {string}
	 */
	email: string;
	/**
	 * @memberof ControllersAuthPostRequest
	 * @type {string}
	 */
	firstName: string;
	/**
	 * @memberof ControllersAuthPostRequest
	 * @type {string}
	 */
	lastName: string;
	/**
	 * @memberof ControllersAuthPostRequest
	 * @type {string}
	 */
	password: string;
}

/** Check if a given object implements the ControllersAuthPostRequest interface. */
export function instanceOfControllersAuthPostRequest(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "email" in value;
	isInstance = isInstance && "firstName" in value;
	isInstance = isInstance && "lastName" in value;
	isInstance = isInstance && "password" in value;

	return isInstance;
}

export function ControllersAuthPostRequestFromJSON(json: any): ControllersAuthPostRequest {
	return ControllersAuthPostRequestFromJSONTyped(json, false);
}

export function ControllersAuthPostRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ControllersAuthPostRequest {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		email: json["email"],
		firstName: json["firstName"],
		lastName: json["lastName"],
		password: json["password"],
	};
}

export function ControllersAuthPostRequestToJSON(value?: ControllersAuthPostRequest | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		email: value.email,
		firstName: value.firstName,
		lastName: value.lastName,
		password: value.password,
	};
}
