/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AuthClaims } from "./AuthClaims";
import { AuthClaimsFromJSON, AuthClaimsFromJSONTyped, AuthClaimsToJSON } from "./AuthClaims";

/**
 * @export
 * @interface ControllersAuthGetResponse
 */
export interface ControllersAuthGetResponse {
	/**
	 * @memberof ControllersAuthGetResponse
	 * @type {AuthClaims}
	 */
	claims: AuthClaims;
}

/** Check if a given object implements the ControllersAuthGetResponse interface. */
export function instanceOfControllersAuthGetResponse(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "claims" in value;

	return isInstance;
}

export function ControllersAuthGetResponseFromJSON(json: any): ControllersAuthGetResponse {
	return ControllersAuthGetResponseFromJSONTyped(json, false);
}

export function ControllersAuthGetResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ControllersAuthGetResponse {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		claims: AuthClaimsFromJSON(json["claims"]),
	};
}

export function ControllersAuthGetResponseToJSON(value?: ControllersAuthGetResponse | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		claims: AuthClaimsToJSON(value.claims),
	};
}
