/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ModelsBook } from "./ModelsBook";
import { ModelsBookFromJSON, ModelsBookFromJSONTyped, ModelsBookToJSON } from "./ModelsBook";

/**
 * @export
 * @interface ControllersBooksGetData
 */
export interface ControllersBooksGetData {
	/**
	 * @memberof ControllersBooksGetData
	 * @type {ModelsBook}
	 */
	book: ModelsBook;
}

/** Check if a given object implements the ControllersBooksGetData interface. */
export function instanceOfControllersBooksGetData(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "book" in value;

	return isInstance;
}

export function ControllersBooksGetDataFromJSON(json: any): ControllersBooksGetData {
	return ControllersBooksGetDataFromJSONTyped(json, false);
}

export function ControllersBooksGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBooksGetData {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		book: ModelsBookFromJSON(json["book"]),
	};
}

export function ControllersBooksGetDataToJSON(value?: ControllersBooksGetData | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		book: ModelsBookToJSON(value.book),
	};
}
