/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * @export
 * @interface ControllersBooksPostRequest
 */
export interface ControllersBooksPostRequest {
	/**
	 * @memberof ControllersBooksPostRequest
	 * @type {string}
	 */
	author: string;
	/**
	 * @memberof ControllersBooksPostRequest
	 * @type {string}
	 */
	finishedAt?: string;
	/**
	 * @memberof ControllersBooksPostRequest
	 * @type {string}
	 */
	purchasedAt?: string;
	/**
	 * @memberof ControllersBooksPostRequest
	 * @type {number}
	 */
	rating?: number;
	/**
	 * @memberof ControllersBooksPostRequest
	 * @type {string}
	 */
	title: string;
	/**
	 * @memberof ControllersBooksPostRequest
	 * @type {string}
	 */
	userId?: string;
}

/** Check if a given object implements the ControllersBooksPostRequest interface. */
export function instanceOfControllersBooksPostRequest(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "author" in value;
	isInstance = isInstance && "title" in value;

	return isInstance;
}

export function ControllersBooksPostRequestFromJSON(json: any): ControllersBooksPostRequest {
	return ControllersBooksPostRequestFromJSONTyped(json, false);
}

export function ControllersBooksPostRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ControllersBooksPostRequest {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		author: json["author"],
		finishedAt: !exists(json, "finishedAt") ? undefined : json["finishedAt"],
		purchasedAt: !exists(json, "purchasedAt") ? undefined : json["purchasedAt"],
		rating: !exists(json, "rating") ? undefined : json["rating"],
		title: json["title"],
		userId: !exists(json, "userId") ? undefined : json["userId"],
	};
}

export function ControllersBooksPostRequestToJSON(value?: ControllersBooksPostRequest | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		author: value.author,
		finishedAt: value.finishedAt,
		purchasedAt: value.purchasedAt,
		rating: value.rating,
		title: value.title,
		userId: value.userId,
	};
}
