/* tslint:disable */
/* eslint-disable */
/**
 * Some API
 * This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HttputilHTTPErrorError } from './HttputilHTTPErrorError';
import {
    HttputilHTTPErrorErrorFromJSON,
    HttputilHTTPErrorErrorFromJSONTyped,
    HttputilHTTPErrorErrorToJSON,
} from './HttputilHTTPErrorError';

/**
 * 
 * @export
 * @interface HttputilHTTPError
 */
export interface HttputilHTTPError {
    /**
     * 
     * @type {HttputilHTTPErrorError}
     * @memberof HttputilHTTPError
     */
    error?: HttputilHTTPErrorError;
}

/**
 * Check if a given object implements the HttputilHTTPError interface.
 */
export function instanceOfHttputilHTTPError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HttputilHTTPErrorFromJSON(json: any): HttputilHTTPError {
    return HttputilHTTPErrorFromJSONTyped(json, false);
}

export function HttputilHTTPErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttputilHTTPError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : HttputilHTTPErrorErrorFromJSON(json['error']),
    };
}

export function HttputilHTTPErrorToJSON(value?: HttputilHTTPError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': HttputilHTTPErrorErrorToJSON(value.error),
    };
}

