/* tslint:disable */
/* eslint-disable */
/**
 * Some API This is a sample server celler server.
 *
 * The version of the OpenAPI document: 1.0 Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * @export
 * @interface JwtNumericDate
 */
export interface JwtNumericDate {
	/**
	 * @memberof JwtNumericDate
	 * @type {string}
	 */
	timeTime?: string;
}

/** Check if a given object implements the JwtNumericDate interface. */
export function instanceOfJwtNumericDate(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function JwtNumericDateFromJSON(json: any): JwtNumericDate {
	return JwtNumericDateFromJSONTyped(json, false);
}

export function JwtNumericDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtNumericDate {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		timeTime: !exists(json, "time.Time") ? undefined : json["time.Time"],
	};
}

export function JwtNumericDateToJSON(value?: JwtNumericDate | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		"time.Time": value.timeTime,
	};
}
