# fly.toml app configuration file generated for pms-kratos on 2023-06-15T09:20:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pms-kratos"
primary_region = "ord"

[build]
  image = "registry.fly.io/pms-kratos:test"

[http_service]
  internal_port = 4455
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
