version = "v0.13.0"
dsn = "memory"

[serve.public]
base_url = "https://0.0.0.0:4433/"

  [serve.public.cors]
  enabled = true

[serve.admin]
base_url = "https://0.0.0.0:4434/"

[selfservice]
default_browser_return_url = "https://0.0.0.0:4455/"
allowed_return_urls = [ "https://0.0.0.0:4455" ]

[selfservice.methods.password]
enabled = true

[selfservice.methods.totp]
enabled = true

  [selfservice.methods.totp.config]
  issuer = "Kratos"

[selfservice.methods.lookup_secret]
enabled = true

[selfservice.methods.link]
enabled = true

[selfservice.methods.code]
enabled = true

[selfservice.flows.error]
ui_url = "https://0.0.0.0:4455/error"

[selfservice.flows.settings]
ui_url = "https://0.0.0.0:4455/settings"
privileged_session_max_age = "15m"
required_aal = "highest_available"

[selfservice.flows.recovery]
enabled = true
ui_url = "https://0.0.0.0:4455/recovery"
use = "code"

[selfservice.flows.verification]
enabled = true
ui_url = "https://0.0.0.0:4455/verification"
use = "code"

  [selfservice.flows.verification.after]
  default_browser_return_url = "https://0.0.0.0:4455/"

[selfservice.flows.logout.after]
default_browser_return_url = "https://0.0.0.0:4455/login"

[selfservice.flows.login]
ui_url = "https://0.0.0.0:4455/login"
lifespan = "10m"

[selfservice.flows.registration]
lifespan = "10m"
ui_url = "https://0.0.0.0:4455/registration"

[[selfservice.flows.registration.after.password.hooks]]
hook = "session"

[[selfservice.flows.registration.after.password.hooks]]
hook = "show_verification_ui"

[log]
level = "debug"
format = "text"
leak_sensitive_values = true

[secrets]
cookie = [ "PLEASE-CHANGE-ME-I-AM-VERY-INSECURE" ]
cipher = [ "32-LONG-SECRET-NOT-SECURE-AT-ALL" ]

[ciphers]
algorithm = "xchacha20-poly1305"

[hashers]
algorithm = "bcrypt"

  [hashers.bcrypt]
  cost = 8

[identity]
default_schema_id = "default"

  [[identity.schemas]]
  id = "default"
  url = "file:///home/ory/identity.schema.json"

[courier.smtp]
connection_uri = "smtps://test:test@mailslurper:1025/?skip_ssl_verify=true"
